Add missing types definition
This fixes typescript import error:
> Cannot find module 'unixcrypt' or its corresponding type declarations.
when doing `import { encrypt } from 'unixcrypt';`